trigger:
  branches:
    exclude:
    - master
  tags:
    include:
    - '*'
    exclude:
    - '*-test*'

stages:
- stage: test
  displayName: 'Build & Test'
  jobs:
  - job: macos
    strategy:
      matrix:
        macosSwift55:
          imageName: 'macOS-12'
          DEVELOPER_DIR: '/Applications/Xcode_13.2.1.app'
          IOS_SIMULATOR: 'iPhone 8'
          WATCHOS_SIMULATOR: 'Apple Watch Series 6 - 44mm'
        macosSwift56:
          imageName: 'macOS-12'
          DEVELOPER_DIR: '/Applications/Xcode_13.4.1.app'
          IOS_SIMULATOR: 'iPhone 8'
          WATCHOS_SIMULATOR: 'Apple Watch Series 6 - 44mm'
        macosSwift57:
          imageName: 'macOS-13'
          DEVELOPER_DIR: '/Applications/Xcode_14.2.app'
          IOS_SIMULATOR: 'iPhone 14'
          WATCHOS_SIMULATOR: 'Apple Watch Series 6 (44mm)'
        macosSwift58:
          imageName: 'macOS-13'
          DEVELOPER_DIR: '/Applications/Xcode_14.3.1.app'
          IOS_SIMULATOR: 'iPhone 14'
          WATCHOS_SIMULATOR: 'Apple Watch Series 6 (44mm)'
        macosSwift59:
          imageName: 'macOS-13'
          DEVELOPER_DIR: '/Applications/Xcode_15.2.app'
          IOS_SIMULATOR: 'iPhone 14'
          WATCHOS_SIMULATOR: 'Apple Watch Series 6 (44mm)'
        # TODO: Enable when AZP adds macOS 14 images.
        # macosSwift510:
        #   imageName: 'macOS-14'
        #   DEVELOPER_DIR: '/Applications/Xcode_15.3.app'
        #   IOS_SIMULATOR: 'iPhone 14'
        #   WATCHOS_SIMULATOR: 'Apple Watch Series 6 (44mm)'
    pool:
      vmImage: $(imageName)
    steps:
    - script: |
        set -e -o xtrace
        swift --version
        swift build
        swift test --filter BitByteDataTests
      displayName: 'Build & Test'
    - script: |
        set -e -o xtrace
        swift --version
        swift build -c release # Check Release build just in case.
      displayName: 'Build Release'
    - script: |
        set -e -o xtrace
        xcodebuild -version
        xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=OS X" clean test
        xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=iOS Simulator,name=$IOS_SIMULATOR" clean test
        xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=watchOS Simulator,name=$WATCHOS_SIMULATOR" clean test
        xcodebuild -quiet -project BitByteData.xcodeproj -scheme BitByteData -destination "platform=tvOS Simulator,name=Apple TV" clean test
      displayName: 'Build & Test Darwin Platforms'
  - job: linux
    strategy:
      matrix:
        linuxSwift55:
          imageName: 'ubuntu-20.04'
          containerImage: 'swift:5.5.3-focal'
        linuxSwift56:
          imageName: 'ubuntu-20.04'
          containerImage: 'swift:5.6.3-focal'
        linuxSwift57:
          imageName: 'ubuntu-20.04'
          containerImage: 'swift:5.7.3-focal'
        linuxSwift58:
          imageName: 'ubuntu-20.04'
          containerImage: 'swift:5.8.1-focal'
        linuxSwift59:
          imageName: 'ubuntu-20.04'
          containerImage: 'swift:5.9.2-focal'
        linuxSwift510:
          imageName: 'ubuntu-20.04'
          containerImage: 'swift:5.10-focal'
    pool:
      vmImage: $(imageName)
    container: $[ variables['containerImage'] ]
    steps:
    - script: |
        set -e -o xtrace
        swift --version
        swift build
        swift test --filter BitByteDataTests
      displayName: 'Build & Test'
    - script: |
        set -e -o xtrace
        swift --version
        swift build -c release # Check Release build just in case.
      displayName: 'Build Release'
  - job: windows
    strategy:
      matrix:
        windowsSwift55:
          imageName: 'windows-2019'
          SWIFT_VERSION: '5.5.3'
          ICU_PATH: 'C:\Library\icu-67\usr\bin'
          SWIFT_DEV_PATH: 'C:\Library\Swift-development\bin'
          XCTEST_LIB_PATH: ''
        windowsSwift56:
          imageName: 'windows-2019'
          SWIFT_VERSION: '5.6.3'
          ICU_PATH: 'C:\Library\icu-69.1\usr\bin'
          SWIFT_DEV_PATH: 'C:\Library\Swift-development\bin'
          XCTEST_LIB_PATH: ''
        windowsSwift57:
          imageName: 'windows-2019'
          SWIFT_VERSION: '5.7.3'
          ICU_PATH: 'C:\Program Files\swift\icu-69.1\usr\bin'
          SWIFT_DEV_PATH: 'C:\Program Files\swift\runtime-development\usr\bin'
          XCTEST_LIB_PATH: '\x86_64'
        windowsSwift58:
          imageName: 'windows-2019'
          SWIFT_VERSION: '5.8.1'
          ICU_PATH: 'C:\Program Files\swift\icu-69.1\usr\bin'
          SWIFT_DEV_PATH: 'C:\Program Files\swift\runtime-development\usr\bin'
          XCTEST_LIB_PATH: '\x86_64'
        windowsSwift59:
          imageName: 'windows-2019'
          SWIFT_VERSION: '5.9.2'
          ICU_PATH: 'C:\Program Files\swift\icu-69.1\usr\bin'
          SWIFT_DEV_PATH: 'C:\Program Files\swift\runtime-development\usr\bin'
          XCTEST_LIB_PATH: '\x86_64'
        # TODO: There seems to be an unknown problem with the Swift installation step.
        # windowsSwift510:
        #   imageName: 'windows-2019'
        #   SWIFT_VERSION: '5.10'
        #   ICU_PATH: 'C:\Program Files\swift\icu-69.1\usr\bin'
        #   SWIFT_DEV_PATH: 'C:\Program Files\swift\runtime-development\usr\bin'
        #   XCTEST_LIB_PATH: '\x86_64'
    pool:
      vmImage: $(imageName)
    variables:
      DEVELOPER_DIR: 'C:\Library\Developer'
      SDKROOT: 'C:\Library\Developer\Platforms\Windows.platform\Developer\SDKs\Windows.sdk'
      SWIFTFLAGS: '--sdk $(SDKROOT)'
      XCTEST_DIR: 'C:\Library\Developer\Platforms\Windows.platform\Developer\Library\XCTest-development'
      SWIFTTESTFLAGS: '-Xswiftc -I -Xswiftc $(XCTEST_DIR)\usr\lib\swift\windows\x86_64 -Xswiftc -L -Xswiftc $(XCTEST_DIR)\usr\lib\swift\windows$(XCTEST_LIB_PATH) -Xswiftc -sdk -Xswiftc $(SDKROOT)'
    steps:
    - pwsh: Invoke-WebRequest -Uri https://swift.org/builds/swift-$(SWIFT_VERSION)-release/windows10/swift-$(SWIFT_VERSION)-RELEASE/swift-$(SWIFT_VERSION)-RELEASE-windows10.exe -OutFile swift-install.exe
      displayName: 'Download Swift'
    - task: BatchScript@1
      inputs:
        filename: .\swift-install.exe
        arguments: /install /quiet
        modifyEnvironment: true
      displayName: 'Install Swift'
    - script: |
        set PATH=C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin;%SWIFT_DEV_PATH%;%ICU_PATH%;%PATH%
        swift.exe --version
        swift.exe build %SWIFTFLAGS% || exit /b %errorlevel%
        swift.exe test --filter BitByteDataTests %SWIFTFLAGS% %SWIFTTESTFLAGS% || exit /b %errorlevel%
      displayName: 'Build & Test'
    - script: |
        set PATH=C:\Library\Developer\Toolchains\unknown-Asserts-development.xctoolchain\usr\bin;%SWIFT_DEV_PATH%;%ICU_PATH%;%PATH%
        swift.exe --version
        swift.exe build -c release %SWIFTFLAGS% || exit /b %errorlevel%
      displayName: 'Build Release'
- stage: deploy
  displayName: Deploy
  dependsOn: test
  # Deploy on tags only; test tags are excluded in trigger section.
  condition: and(not(eq(variables['Build.Reason'], 'PullRequest')), startsWith(variables['Build.SourceBranch'], 'refs/tags'))
  jobs:
  - job: ghPages
    displayName: 'Publish API docs to GH Pages'
    pool:
      vmImage: 'macOS-12'
    variables:
      DEVELOPER_DIR: '/Applications/Xcode_14.2.app'
    steps:
    - script: |
        set -e -o xtrace
        brew update
        brew install sourcekitten
        gem install -N jazzy
      displayName: 'Install Tools'
    - task: InstallSSHKey@0
      inputs:
        knownHostsEntry: 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk='
        sshPublicKey: '$(bbdPubDeployKey)'
        sshKeySecureFile: 'bbd_deploy_key'
      displayName: 'Install an SSH key'
    - script: git worktree add docs gh-pages
      displayName: 'Prepare Worktree'
    - script: |
        sourcekitten doc --spm --module-name BitByteData > docs.json
        jazzy
      displayName: 'Before Deploy'
    - script: |
        set -e -o xtrace
        git config --local user.name "Azure Pipelines"
        git config --local user.email "azuredevops@microsoft.com"
        cd docs
        git add --all
        git commit -m "Deploy to GH Pages [skip ci]" --amend
        cd ..
        git remote set-url --push origin git@github.com:tsolomko/BitByteData.git
        git push --force origin gh-pages:gh-pages
      displayName: 'Deploy to GH Pages'
