#if !canImport(ObjectiveC)
import XCTest

extension BigEndianByteReaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__BigEndianByteReaderTests = [
        ("testByte", testByte),
        ("testBytes", testBytes),
        ("testBytesLeft", testBytesLeft),
        ("testBytesRead", testBytesRead),
        ("testIntFromBytes", testIntFromBytes),
        ("testIsFinished", testIsFinished),
        ("testNonZeroStartIndex", testNonZeroStartIndex),
        ("testUint16", testUint16),
        ("testUint16FromBytes", testUint16FromBytes),
        ("testUint32", testUint32),
        ("testUint32FromBytes", testUint32FromBytes),
        ("testUint64", testUint64),
        ("testUint64FromBytes", testUint64FromBytes),
    ]
}

extension LittleEndianByteReaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LittleEndianByteReaderTests = [
        ("testByte", testByte),
        ("testBytes", testBytes),
        ("testBytesLeft", testBytesLeft),
        ("testBytesRead", testBytesRead),
        ("testIntFromBytes", testIntFromBytes),
        ("testIsFinished", testIsFinished),
        ("testNonZeroStartIndex", testNonZeroStartIndex),
        ("testUint16", testUint16),
        ("testUint16FromBytes", testUint16FromBytes),
        ("testUint32", testUint32),
        ("testUint32FromBytes", testUint32FromBytes),
        ("testUint64", testUint64),
        ("testUint64FromBytes", testUint64FromBytes),
    ]
}

extension LsbBitReaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LsbBitReaderTests = [
        ("testAdvance", testAdvance),
        ("testAlign", testAlign),
        ("testBit", testBit),
        ("testBitReaderByte", testBitReaderByte),
        ("testBitReaderBytes", testBitReaderBytes),
        ("testBitReaderIntFromBytes", testBitReaderIntFromBytes),
        ("testBitReaderNonZeroStartIndex", testBitReaderNonZeroStartIndex),
        ("testBitReaderUint16", testBitReaderUint16),
        ("testBitReaderUint32FromBytes", testBitReaderUint32FromBytes),
        ("testBits", testBits),
        ("testBitsLeft", testBitsLeft),
        ("testBitsRead", testBitsRead),
        ("testByteFromBits", testByteFromBits),
        ("testBytesLeft", testBytesLeft),
        ("testBytesRead", testBytesRead),
        ("testConvertedByteReader", testConvertedByteReader),
        ("testIntFromBits", testIntFromBits),
        ("testIsAligned", testIsAligned),
        ("testUint16FromBits", testUint16FromBits),
        ("testUint32FromBits", testUint32FromBits),
        ("testUint64FromBits", testUint64FromBits),
    ]
}

extension LsbBitWriterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LsbBitWriterTests = [
        ("testAlign", testAlign),
        ("testAppendByte", testAppendByte),
        ("testIsAligned", testIsAligned),
        ("testNamingConsistency", testNamingConsistency),
        ("testWriteBit", testWriteBit),
        ("testWriteBitsArray", testWriteBitsArray),
        ("testWriteNumber", testWriteNumber),
        ("testWriteUnsignedNumber", testWriteUnsignedNumber),
    ]
}

extension MsbBitReaderTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MsbBitReaderTests = [
        ("testAdvance", testAdvance),
        ("testAlign", testAlign),
        ("testBit", testBit),
        ("testBitReaderByte", testBitReaderByte),
        ("testBitReaderBytes", testBitReaderBytes),
        ("testBitReaderIntFromBytes", testBitReaderIntFromBytes),
        ("testBitReaderNonZeroStartIndex", testBitReaderNonZeroStartIndex),
        ("testBitReaderUint16", testBitReaderUint16),
        ("testBitReaderUint32FromBytes", testBitReaderUint32FromBytes),
        ("testBits", testBits),
        ("testBitsLeft", testBitsLeft),
        ("testBitsRead", testBitsRead),
        ("testByteFromBits", testByteFromBits),
        ("testBytesLeft", testBytesLeft),
        ("testBytesRead", testBytesRead),
        ("testConvertedByteReader", testConvertedByteReader),
        ("testIntFromBits", testIntFromBits),
        ("testIsAligned", testIsAligned),
        ("testUint16FromBits", testUint16FromBits),
        ("testUint32FromBits", testUint32FromBits),
        ("testUint64FromBits", testUint64FromBits),
    ]
}

extension MsbBitWriterTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__MsbBitWriterTests = [
        ("testAlign", testAlign),
        ("testAppendByte", testAppendByte),
        ("testIsAligned", testIsAligned),
        ("testNamingConsistency", testNamingConsistency),
        ("testWriteBit", testWriteBit),
        ("testWriteBitsArray", testWriteBitsArray),
        ("testWriteNumber", testWriteNumber),
        ("testWriteUnsignedNumber", testWriteUnsignedNumber),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(BigEndianByteReaderTests.__allTests__BigEndianByteReaderTests),
        testCase(LittleEndianByteReaderTests.__allTests__LittleEndianByteReaderTests),
        testCase(LsbBitReaderTests.__allTests__LsbBitReaderTests),
        testCase(LsbBitWriterTests.__allTests__LsbBitWriterTests),
        testCase(MsbBitReaderTests.__allTests__MsbBitReaderTests),
        testCase(MsbBitWriterTests.__allTests__MsbBitWriterTests),
    ]
}
#endif
